microblog/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.shortcuts import redirect



urlpatterns = [
    # path('', lambda req: redirect('posts/')),
    path('', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path, include

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostsIndexView.as_view(), name='index'),
    path('create/', views.create_post, name='create-post'),
    path('<int:pk>/', include([
        path('', views.PostsDetailView.as_view(), name='detail'),
        path('delete', views.PostsDeleteView.as_view(), name='delete-post'),
        path('update', views.PostUpdateView.as_view(), name='update-post'),
        path('delete/comment', views.CommentsDeleteView.as_view(), name='delete-comment')
    ])),
    path('<int:post_id>/comment/', include([
        path('', views.create_comment, name='create-comment')
    ])),
    path('<int:object_id>/<str:object_type>/reaction/', views.toggle_reaction, name='toggle-reaction')
]

profiles/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from haystack.views import basic_search
from . import views


app_name = 'profiles'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url( r'^login/$', views.signin, name="login"),
    url( r'^logout/$', views.logout_view, name="logout"),
    url(r'search/$', login_required(basic_search), name='basic_search'),
    url(r'search-autocomplete/$', views.user_search_autocomplete, name='autocomplete'),
    # path('<str:keyword>/search', views.SearchUserIndexView.as_view(), name='user-search'),
    path('<int:requestee_id>/friend-request', views.request_friendship, name='friend-request'),
    path('<int:pk>/', include([
        path('', views.ProfileDetailView.as_view(), name='detail'),
        path('friend-request-update', views.FriendshipUpdateView.as_view(), name='friend-request-update'),
        path('friend-list', views.FriendshipIndexView.as_view(), name='friend-list'),
        path('<int:suggestion_count>/friend-suggestion', views.FriendshipSuggestionIndexView.as_view(),
             name='friend-suggestion'),
        path('friendship-delete', views.FriendshipDeleteView.as_view(), name='delete-friendship'),
    ]))
]

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <div class="navbar-left-side d-flex align-items-center">
    <a href="{% url 'posts:index' %}">Home</a>
  </div>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center d-flex justify-content-end">
      <li class="nav-item active">
           <a href="{% url 'profiles:detail' user.id %}">Profile</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'profiles:logout' %}">Logout</a>
      </li>
        <li class="nav-item">
        <a href="{% url 'profiles:friend-suggestion' pk=user.id suggestion_count=10 %}">Find Friends</a>
      </li>
      <li>
               {% include 'search/partials/_profile_search_form.html'  %}
      </li>
    </ul>

  </div>
</nav>

templates/partials/_pagination.html

    {% if object_list %}
    <section class="mt-3">

    <nav aria-label="Page navigation example ">
          <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><</a>
                </li>
              {% endif %}

              {% for i in page_obj.paginator.page_range %}
            <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link " href="?page={{ i }}">{{i}}</a></li>
              {% endfor %}

              {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true"> > </span>
              </a>
            </li>
              <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
              {% endif %}

          </ul>
        </nav>

        <p class="text-center">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}. </p>
        </section>
        {% endif %}