microblog/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.shortcuts import redirect



urlpatterns = [
    # path('', lambda req: redirect('posts/')),
    path('', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path, include

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostsIndexView.as_view(), name='index'),
    path('create/', views.create_post, name='create-post'),
    path('<int:pk>/', include([
        path('', views.PostsDetailView.as_view(), name='detail'),
        path('delete', views.PostsDeleteView.as_view(), name='delete-post'),
        path('update', views.PostUpdateView.as_view(), name='update-post'),
        path('delete/comment', views.CommentsDeleteView.as_view(), name='delete-comment')
    ])),
    path('<int:post_id>/comment/', include([
        path('', views.create_comment, name='create-comment')
    ])),
    path('<int:object_id>/<str:object_type>/reaction/', views.toggle_reaction, name='toggle-reaction')
]

profiles/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from haystack.views import basic_search
from . import views


app_name = 'profiles'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url( r'^login/$', views.signin, name="login"),
    url( r'^logout/$', views.logout_view, name="logout"),
    url(r'search/$', login_required(basic_search), name='basic_search'),
    url(r'search-autocomplete/$', views.user_search_autocomplete, name='autocomplete'),
    # path('<str:keyword>/search', views.SearchUserIndexView.as_view(), name='user-search'),
    path('<int:requestee_id>/friend-request', views.request_friendship, name='friend-request'),
    path('<int:pk>/', include([
        path('', views.ProfileDetailView.as_view(), name='detail'),
        path('friend-request-update', views.FriendshipUpdateView.as_view(), name='friend-request-update'),
        path('friend-list', views.FriendshipIndexView.as_view(), name='friend-list'),
        path('<int:suggestion_count>/friend-suggestion', views.FriendshipSuggestionIndexView.as_view(),
             name='friend-suggestion'),
        path('friendship-delete', views.FriendshipDeleteView.as_view(), name='delete-friendship'),
    ]))
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

FRIENDSHIP_STATUS_CHOICES = (
                  ("Pending", "Pending"),
                  ("Accept", "Accept"),
                  ("Decline", "Decline")
)

class Profile(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50, default="Miami")
    state = models.CharField(max_length=50, default="FL")
    birthday = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    @receiver(post_save, sender=User)

    def update_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
        instance.profile.save()

    def __str__(self):
            return self.first_name + " " + self.last_name

class Friendship(models.Model):
      status = models.CharField(max_length=50, choices=FRIENDSHIP_STATUS_CHOICES, default="Pending")
      requester = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='requester')
      requestee = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='requestee')

      class Meta:
        unique_together = ('requester', 'requestee')

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
import datetime
#from django.contrib.auth import LoginView
from .models import Friendship

STATUS_CHOICES = (
                  ("Accept", "Accept"),
                  ("Decline", "Decline"))

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    address = forms.CharField(max_length=30, required=True)
    city = forms.CharField(max_length=30, required=True)
    state = forms.CharField(max_length=30, required=True)
    birthday = forms.DateField(initial=datetime.date.today, required=True, widget=forms.SelectDateWidget())
    email = forms.EmailField(max_length=254, required=True, widget=forms.TextInput(attrs={'placeholder': 'E.g. example@aol.com'}) )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

class FriendshipRequestForm(forms.ModelForm):
    class Meta:
        model = Friendship
        fields = ('status',)

    def __init__(self, *args, **kwargs):
        super(FriendshipRequestForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

class FriendshipUpdateForm(forms.ModelForm):
      status = forms.CharField(max_length=30, widget=forms.Select(choices=STATUS_CHOICES), required=True)

      class Meta:
          model = Friendship
          fields = ('status',)

      def __init__(self, *args, **kwargs):
          super(FriendshipUpdateForm, self).__init__(*args, **kwargs)
          ## add a "form-control" class to each form input
          ## for enabling bootstrap
          for name in self.fields.keys():
              self.fields[name].widget.attrs.update({
                  'class': 'form-control',
              })



profiles/views.py
# Create your views here.
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from profiles.forms import SignUpForm, FriendshipRequestForm, FriendshipUpdateForm
from django.views import generic
from django.contrib.auth.models import User
from .models import Profile, Friendship
from posts.models import Post
from posts.forms import CommentsForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from django.db import IntegrityError
from profiles.utils.mixins import UserIsRequesteeMixin, UserIsRequesteeOrRequesterMixin
from profiles.utils.utils import get_friendlist, get_friend_suggestions, get_mutual_friends, check_friendship_status
import simplejson as json
from haystack.query import SearchQuerySet
import pdb

def signup(request):
    '''
    Function is to create new profiles and at the same time creates new users
    :param request:
    :return:
    '''
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.last_name = form.cleaned_data.get('last_name')
            user.profile.address = form.cleaned_data.get('address')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.state = form.cleaned_data.get('state')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/posts/')
    else:
        form = SignUpForm()

    return render(request, 'profiles/signup.html', {'form': form})

def signin(request):
    '''
    Logs in the user and authenticates them
    :param request:
    :return:
    '''
    form = AuthenticationForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('posts:index')

        else:
            # Return an 'invalid login' error message.
            messages.error(request, 'Username or password not correct.')
            return redirect('profiles:login')

    else:
        return render(request, 'profiles/signin.html', {'form': form})



def logout_view(request):
    '''
    Logout the user function, redirects user to login page
    :param request:
    :return:
    '''
    logout(request)
    return HttpResponseRedirect(reverse('profiles:login'))
    # Redirect to a success page.


class ProfileDetailView(LoginRequiredMixin, generic.DetailView):
    model = Profile
    template_name = 'profiles/detail.html'
    form_class = FriendshipUpdateForm

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        profile = self.get_object()
        user = self.request.user
        profile_belongs_to_user = user.id == self.kwargs["pk"]
        user_friendlist = get_friendlist(self.request.user)

        context['form'] = self.form_class if profile_belongs_to_user else None
        context['comment_form'] = CommentsForm
        context['friendship_update_form'] = FriendshipUpdateForm
        context['is_user_profile'] = profile_belongs_to_user
        context['posts'] = Post.objects.filter(author=profile.user).order_by('-pub_date')[:10]
        context['friend_list'] = user_friendlist
        # pdb.set_trace()
        if context['is_user_profile']:
            pending_friend_requests = Friendship.objects.filter(requestee=self.request.user, status="Pending")
            context['pending_friend_requests'] = pending_friend_requests
        else:
            profile = self.get_object().user
            # context['is_friend_of_user'] = profile in user_friendlist
            context['friendship_status'] = check_friendship_status(user, profile)
            print("Friendship status", vars(context['friendship_status']))

        return context

    def get_queryset(self):
        return Profile.objects


class FriendshipIndexView(LoginRequiredMixin, generic.ListView):
    """
    Returns a list of friends that have been accepted
    """
    template_name = 'friendships/index.html'
    context_object_name = 'accepted_friendlist'
    form_class = FriendshipUpdateForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(FriendshipIndexView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['form'] = self.form_class

        return context

    def get_queryset(self):
        """Return the user's friendlist. """
        user = get_object_or_404(User,pk=self.kwargs["pk"])
        return get_friendlist(user)

class FriendshipSuggestionIndexView(LoginRequiredMixin, generic.ListView):
    """
    Returns a list of suggested friends, not already friends with
    """
    template_name = 'friendships/suggestions.html'
    context_object_name = 'suggested_friendlist'
    form_class = FriendshipRequestForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(FriendshipSuggestionIndexView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['form'] = self.form_class

        return context

    def get_queryset(self):
        """Return the user's friendlist. """
        user = self.request.user
        suggestion_count = self.kwargs["suggestion_count"]
        friend_suggestions = get_friend_suggestions(user, suggestion_count)
        for friend in friend_suggestions:
           friend.mutual_friends = get_mutual_friends(user, friend.user)
        return friend_suggestions



@login_required
def request_friendship(request, requestee_id):
    '''
    Adds a new entry to the friendship table to establish a relationship between users
    :param request:
    :param requestee_id:
    :return:
    '''
    requestee = get_object_or_404(User, pk=requestee_id)
    if request.method == 'POST':
        form = FriendshipRequestForm(request.POST)
        if form.is_valid():
            friend_request = form.save(commit=False)
            friend_request.requester = request.user
            friend_request.requestee = requestee
            friend_request.save()

            messages.success(request, "Friend request has been sent.")
            return HttpResponseRedirect(reverse('posts:index'))
    else:
        return HttpResponseNotFound("404 Route not found.")


class FriendshipUpdateView(LoginRequiredMixin, UserIsRequesteeMixin, generic.UpdateView):
    model = Friendship
    form_class = FriendshipUpdateForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("profiles:detail", kwargs={"pk": self.request.user.id})


class FriendshipDeleteView(LoginRequiredMixin, UserIsRequesteeOrRequesterMixin, generic.DeleteView):
    # specify the model you want to use
    model = Friendship
    # can specify success url
    # url to redirect after successfully
    # deleting object
    def get_success_url(self):
        return reverse("profiles:friend-list", kwargs={"pk": self.request.user.id})

def user_search_autocomplete(request):
    sqs = SearchQuerySet().autocomplete(content_auto=request.GET.get('q', ''))[:5]
    suggestions = [result.title for result in sqs]
    # Make sure you return a JSON object, not a bare list.
    # Otherwise, you could be vulnerable to an XSS attack.
    the_data = json.dumps({
        'results': suggestions
    })
    return HttpResponse(the_data, content_type='application/json')

profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>{{ profile.user.username }}</h1>

    {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

    {% if is_user_profile %}
    This is the current user's profile.
    {% for request in pending_friend_requests %}

    {% include 'profiles/partials/_friendship_update_form.html' with id=request.id %}
    <div>Requested By: {{ request.requester.username }}</div>

    {% endfor %}

    <a href="{% url 'profiles:friend-list' profile.id %}">Friends</a>
    <p>Friend Count: {{ friend_list|length }}</p>

    {% endif %}

    {% if friendship_status|length > 0 and not is_user_profile %}
        {% with friendship_status=friendship_status.0 status=friendship_status.0.status %}

        {{ friendship_status.requester }} {{ user }}
        {% if status == "Accept" %}
        {% include 'friendships/partials/_friendship_delete_form.html' with id=friendship_status.id %}
        {% elif status == "Pending" %}
            {% if user.username == friendship_status.requester.username %}
                <button class="btn btn-secondary disabled">Pending Friend Request</button>
            {% elif user.username == friendship_status.requestee.username %}
                {% include 'profiles/partials/_friendship_update_form.html' with id=friendship_status.id form=friendship_update_form %}
            {% endif %}
        {% endif %}
        {% endwith %}
    {% elif not is_user_profile %}
    {% include 'profiles/partials/_friendship_request_form.html' with id=profile.user.id %}
    {% endif %}

    <div>
        <p>{{profile.first_name }} {{profile.last_name}}</p>
        <p>{{profile.user.email}}</p>
    </div>

    <h2>Recent Posts</h2>
    {% for post in posts %}
    {% include 'posts/partials/_post_article.html' with post=post comment_form=comment_form %}
    {% endfor %}
</div>
{% endblock %}

{% block js_block %}
{% include 'posts/partials/_toggle_reaction_js.html' %}
{% endblock %}

profiles/templates/profiles/signin.html
{% extends "base.html" %}

{% block title %}Login - Microblog{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}
<h2>Log in to My Site</h2>
{% if form.errors %}
<p style="color: red">Your username and password didn't match. Please try again.</p>
{% endif %}
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>

    {% if field.help_text %}
    <p><small style="color: grey">{{ field.help_text }}</small></p>
    {% endif %}
    </p>
    {% endfor %}
    {% if messages %}
    {% for message in messages %}
    <p style="color: red">{{message}}</p>
    {% endfor %}
    {% endif %}
    <button class="btn btn-primary" type="submit">Log in</button>
    <p>
        <a href="{% url 'profiles:signup' %}">New to My Site? Sign up</a>
    </p>

</form>
{% endblock %}

profiles/templates/profiles/signup.html
{% extends "base.html" %}
{% block title %}Register - Microblog{% endblock %}
{% block navbar %}{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button class="btn btn-primary" type="submit">Sign up</button>
    <p>
         <a href="{% url 'profiles:login' %}">Already a user</a>
    </p>

</form>
{% endblock %}