microblog/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.shortcuts import redirect



urlpatterns = [
    # path('', lambda req: redirect('posts/')),
    path('', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path, include

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostsIndexView.as_view(), name='index'),
    path('create/', views.create_post, name='create-post'),
    path('<int:pk>/', include([
        path('', views.PostsDetailView.as_view(), name='detail'),
        path('delete', views.PostsDeleteView.as_view(), name='delete-post'),
        path('update', views.PostUpdateView.as_view(), name='update-post'),
        path('delete/comment', views.CommentsDeleteView.as_view(), name='delete-comment')
    ])),
    path('<int:post_id>/comment/', include([
        path('', views.create_comment, name='create-comment')
    ])),
    path('<int:object_id>/<str:object_type>/reaction/', views.toggle_reaction, name='toggle-reaction')
]

profiles/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from haystack.views import basic_search
from . import views


app_name = 'profiles'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url( r'^login/$', views.signin, name="login"),
    url( r'^logout/$', views.logout_view, name="logout"),
    url(r'search/$', login_required(basic_search), name='basic_search'),
    url(r'search-autocomplete/$', views.user_search_autocomplete, name='autocomplete'),
    # path('<str:keyword>/search', views.SearchUserIndexView.as_view(), name='user-search'),
    path('<int:requestee_id>/friend-request', views.request_friendship, name='friend-request'),
    path('<int:pk>/', include([
        path('', views.ProfileDetailView.as_view(), name='detail'),
        path('friend-request-update', views.FriendshipUpdateView.as_view(), name='friend-request-update'),
        path('friend-list', views.FriendshipIndexView.as_view(), name='friend-list'),
        path('<int:suggestion_count>/friend-suggestion', views.FriendshipSuggestionIndexView.as_view(),
             name='friend-suggestion'),
        path('friendship-delete', views.FriendshipDeleteView.as_view(), name='delete-friendship'),
    ]))
]

posts/models.py
from django.db import models
from django.shortcuts import render, get_object_or_404
# Create your models here.
import datetime
# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType

class Reaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reaction = models.CharField(max_length=10, default="U+1F44D")
    content_object = GenericForeignKey('content_type', 'object_id')
    object_id = models.PositiveIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    def __str__(self):
        return self.reaction

class Post(models.Model):
    post_body = models.CharField(max_length=200)
    post_title = models.CharField(max_length=120)
    pub_date = models.DateTimeField('date published', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    reactions = GenericRelation(Reaction)

    def __str__(self):
        return self.post_title

    def was_published_recently(self):
       now = timezone.now()
       return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Comment(models.Model):
    comment_body = models.CharField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    created_date = models.DateTimeField('date created', null=True, auto_now_add=True,blank=True )
    reactions = GenericRelation(Reaction)

    def __str__(self):
        return self.comment_body

class Tag(models.Model):
    tag = models.CharField(max_length=200)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.tag

posts/forms.py
from django import forms
from .models import Post, Reaction, Comment
from datetime import datetime

class PostsForm(forms.ModelForm):
    post_title = forms.CharField(label='Title', max_length=100, required=True)
    post_body = forms.CharField(label='Body', widget=forms.Textarea, required=True)
    pub_date = forms.DateField(label='Publish Date', initial=datetime.now(),
                               widget=forms.SelectDateWidget(attrs={'class': "d-inline"}))

    class Meta:
            model = Post
            fields = ('post_title', 'post_body',  'pub_date')

    def __init__(self, *args, **kwargs):
        super(PostsForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })


class CommentsForm(forms.ModelForm):
    comment_body = forms.CharField(label='Comment', max_length=120, required=True)

    class Meta:
                model = Comment
                fields = ('comment_body',)

    def __init__(self, *args, **kwargs):
        super(CommentsForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

class ReactionsForm(forms.ModelForm):
    # reaction = forms.CharField(label='Reaction', max_length=100)

    class Meta:
                model = Reaction
                fields = ('reaction',)

    def __init__(self, *args, **kwargs):
        super(ReactionsForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

class PostUpdateForm(forms.ModelForm):
    post_title = forms.CharField(label='Title', max_length=100, required=True)
    post_body = forms.CharField(label='Body', widget=forms.Textarea, required=True)

    class Meta:
                model = Post
                fields = ('post_title', 'post_body')

    def __init__(self, *args, **kwargs):
        super(PostUpdateForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Post, Comment, Reaction
from profiles.models import Friendship
from profiles.utils.utils import get_friendlist
from django.contrib.auth.models import User
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.utils.mixins import UserIsAuthorMixin
from django.views.generic.edit import ModelFormMixin, DeleteView, UpdateView
from posts.forms import PostsForm, CommentsForm, ReactionsForm, PostUpdateForm
from django.contrib import messages
from utils.dictionary_utils import check_existing_dictionary_in_list
from django.contrib.messages.views import SuccessMessageMixin
import pdb
from django.db.models.expressions import Case, When, Value, Exists
from django.db.models import Count, Q
from .decorators import user_is_author

class PostsIndexView(LoginRequiredMixin, generic.ListView ):
    template_name = 'posts/index.html'
    context_object_name = 'latest_post_list'
    form_class = PostsForm
    paginate_by = 10

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(PostsIndexView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['form'] = PostsForm
        context['comment_form'] = CommentsForm

        return context

    def get_queryset(self):
        """Return the last ten posts."""
        # pub_date__lte means less than or equal to, today
        user = self.request.user
        friend_list = get_friendlist(user)

        non_future_post = Q(pub_date__lte=timezone.now())
        post_belongs_to_user = Q(author=user)
        post_belongs_to_friend = Q(author__in=friend_list)
        current_posts = Post.objects.filter(non_future_post & (post_belongs_to_user | post_belongs_to_friend)).order_by('-pub_date')

        # TODO: Allow user to fetch more posts if desired

        for post in current_posts:
            post.is_liked_by_user = check_existing_dictionary_in_list(post.reactions.all(), "user", user)

        return current_posts

class PostsDetailView(LoginRequiredMixin,generic.DetailView):
    """"Returns the specified post, cannot show a post that has not been published yet."""
    model = Post
    template_name = 'posts/detail.html'
    form_class = CommentsForm

    def get_context_data(self, **kwargs):
            # Call the base implementation first to get the context
            context = super(PostsDetailView, self).get_context_data(**kwargs)
            # Create any data and add it to the context
            context['form'] = self.form_class
            post = context['post']
            comments = post.comment_set.all()
            #Checks if the user has liked these comments, used for rendering a like vs unlike button
            context['comments'] = comments.annotate(is_liked_by_user=Count('reactions__reaction', filter=Q(reactions__user=self.request.user)))

            return context

    def get_queryset(self):
            """
            Excludes any questions that aren't published yet.
            """
            post = Post.objects.filter(pub_date__lte=timezone.now())

            post = post.annotate(is_liked_by_user=Count('reactions__reaction', filter=Q(reactions__user=self.request.user)))
            return post


class PostsDeleteView(LoginRequiredMixin, UserIsAuthorMixin, generic.DeleteView):
    # specify the model you want to use
    model = Post
    # can specify success url
    # url to redirect after successfully
    # deleting object
    success_url = "/"

class PostUpdateView(LoginRequiredMixin, UserIsAuthorMixin, generic.UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("posts:detail", kwargs={"pk": pk})

@login_required
def toggle_reaction(request, object_id, object_type):
    user = get_object_or_404(User, pk=request.user.id)
    object = None
    if object_type == "comment":
        object = get_object_or_404(Comment, pk=object_id)
    elif object_type == "post":
        object = get_object_or_404(Post, pk=object_id)

    user_reaction = object.reactions.filter(user=user)
    user_has_reacted_to_object = user_reaction.count() > 0

    if request.method == 'POST' and object and request.is_ajax:
        form = ReactionsForm(request.POST)
        # pdb.set_trace()
        if form.is_valid() and not user_has_reacted_to_object:
            reaction = form.save(commit=False)
            reaction.user = user
            reaction.object_id = object_id
            reaction.content_object = object
            reaction.save()

        elif user_has_reacted_to_object:
            user_reaction.delete()

        updated_count = object.reactions.count()
        return JsonResponse({"object_reaction_count": updated_count}, status=200)
    else:
        return JsonResponse({"error": ""}, status=400)


@login_required
def create_post(request):
    # if this is a POST request we need to process the form data
    user = get_object_or_404(User, pk=request.user.id)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:

        form = PostsForm(request.POST)
        # check whether it's valid:

        if form.is_valid():
            # process the data in form.cleaned_data as required
            post = form.save(commit=False)
            post.author = user
            post.save()
            messages.success(request, 'Form submission successful')
            # redirect to a new URL:
            return redirect('posts:index')
        else:
            messages.error(request, "Error")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PostsForm()

    return render(request, 'posts/index.html', {'form': form})

@login_required
def create_comment(request, post_id):
    user = get_object_or_404(User, pk=request.user.id)
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
            # create a form instance and populate it with data from the request:

            form = CommentsForm(request.POST)
            # check whether it's valid:

            if form.is_valid():
                # process the data in form.cleaned_data as required
                comment = form.save(commit=False)
                comment.author = user
                comment.post = post
                comment.save()
                messages.success(request, 'Comment submission successful')
                # redirect to a new URL:
                return redirect(reverse('posts:detail', args=(post.id,)))
            else:
                messages.error(request, "Error")

    else:
        form = PostsForm()

        return render(request, 'posts/index.html', {'form': form})

class CommentsDeleteView(LoginRequiredMixin, UserIsAuthorMixin, SuccessMessageMixin, generic.DeleteView):
    # specify the model you want to use
    model = Comment
    success_message = "Comment was deleted successfully"

    def get_success_url(self):
        post_id = self.get_object().post.id
        messages.success(self.request, self.success_message)
        return reverse("posts:detail", kwargs={"pk": post_id})

posts/templates/posts/partials/_comments_delete.html

<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-danger align-self-end" data-bs-toggle="modal" data-bs-target="#delete_comment_modal_{{id}}">
  Delete Comment
</button>

<!-- Modal -->
<div id="delete_comment_modal_{{id}}" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Modal Header</h4>
        <button type="button" class="close" data-bs-dismiss="modal">&times;</button>

      </div>
      <div class="modal-body d-flex flex-column align-items-center">
         <p>Are you sure you want to delete?</p>
    <form class="delete-comment-form" method="post" action="{% url 'posts:delete-comment' id %}">
    {% csrf_token %}

    <button class="btn btn-danger"  type="submit">Yes</button>
    <button class="btn btn-secondary" data-bs-dismiss="modal">No</button>
    </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>




posts/templates/posts/partials/_comments_delete_js.html
<script>
    const DELETE_COMMENT_BUTTONS = document.getElementsByClassName('delete-comment-button');
    const DELETE_COMMENT_MODALS = document.getElementsByClassName('delete-comment-modal');
    const DELETE_COMMENT_FORMS = document.getElementsByClassName('delete-comment-form');

    let toggleModal = (modal) => {
        console.log("Toggling!");
        modal.classList.toggle("open");
        console.log("It worked!");
    }

    let deleteComment = (e) => {
        e.preventDefault();
    }




</script>

posts/templates/posts/partials/_comments_new.html
<form method="post" action="{% url 'posts:create-comment' id %}" class="mt-3">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button class="btn btn-success" type="submit">Comment</button>
</form>

posts/templates/posts/partials/_post_article.html
<article class="mb-5 border border-dark rounded p-4">
    <h4><a href="{% url 'posts:detail' post.id %}">{{ post.post_title }}</a></h4>
    <p>By: <a href="{% url 'profiles:detail' post.author.id %}">{{post.author.username}}</a></p>
    <p>{{post.post_body}}</p>
    <h6 class="text-secondary">Publish Date: {{post.pub_date|date:"M d, Y" }}</h6>

    {% include 'posts/partials/_toggle_reaction.html' with id=post.id is_liked=post.is_liked_by_user type="post" reaction_count=post.reactions.count %}

    {% include 'posts/partials/_comments_new.html' with id=post.id form=comment_form %}

</article>

posts/templates/posts/partials/_posts_new.html
<form method="post" action="{% url 'posts:create-post' %}">
    {% csrf_token %}

    {% for field in form %}
<!--        {{ field.label_tag }}-->
    <p class="{% if field.label_tag == 'Publish Date:' %} d-flex {% endif %}">
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button class="btn btn-primary d-block col-12" type="submit">Post</button>
</form>

posts/templates/posts/partials/_toggle_reaction.html

<form class="reaction__form me-3"
      id="reaction_{{id}}"
      data-reaction-id="{{id}}"
      data-post-type="{{type}}"
      method="POST"
      action={% url 'posts:toggle-reaction' object_id=id object_type=type %}
      data-reaction-count="{{reaction_count | default_if_none:'0' }}" >

<!--            method="post" action="/posts/{{id}}/{{type}}/reaction/"-->

    {% csrf_token %}
        <div >Like Count: <span id="reaction__count__{{id}}">{{reaction_count | default_if_none:"0" }}</span></div>
    <input type="hidden" name="reaction" value="U+1F44D" />

    <button type="submit"
           id="reaction__button__{{id}}"
           class="reaction__button mt-2 btn btn-{% if is_liked > 0 %}primary{% else %}secondary{% endif %}" >
        {% if is_liked > 0 %}
        Unlike
        {% else %}
        Like
        {% endif %}
    </button>
</form>


posts/templates/posts/partials/_toggle_reaction_js.html
<script>

    let reaction_forms = $('.reaction__form');
    let reaction_buttons = document.getElementsByClassName('reaction__button');

    // Used to update the styling of the reaction button
    let updateReactionButtonStyle = (id)=> {
        let button = $(`#reaction__button__${id}`);
        button.toggleClass("btn-secondary btn-primary");

        button.text() === "Like" ? button.text("Unlike") :  button.text("Like");
    }

    let updateLikeCount = (id, updatedCount)=> {
        let like_count_div = $(`#reaction__count__${id}`);
        like_count_div.text(`${updatedCount}`)
    }


    let toggleLike = (e, id, type) => {

        let serializedData = $(e).serialize();

        //Check button's current status
        let currentLikeStatus = document.getElementById(`reaction__button__${id}`).textContent == "Like";

        console.log("Text content", currentLikeStatus);

        $.ajax({
            type: 'POST',
            url:  `{% url 'posts:toggle-reaction' object_id=9998 object_type=9999 %}`.replace(9998, id).replace(9999, type),
            data: serializedData,
            success: function (response) {

                let updated_count = JSON.parse(response['object_reaction_count']);
                updateLikeCount(id, updated_count);
                updateReactionButtonStyle(id);

            },
            error: function (response) {
                // alert the error if any error occurred
                alert(response["responseJSON"]["error"]);
            }
        })


        //Depending on what they change it to increment or decrement the count
    }


<!--    Assign the on submits -->
    reaction_forms.each((i, form)=>{
        let reaction_id = $(form).data('reactionId');
        let post_type = $(form).data('postType');
        $(form).submit((e)=> {
            e.preventDefault();
            toggleLike(form, reaction_id, post_type);
        });
    });

</script>